-- ============================================
-- Rally MVP — Supabase Schema
-- Run this in Supabase SQL Editor (supabase.com → your project → SQL Editor)
-- ============================================

-- Enable UUID generation
create extension if not exists "uuid-ossp";

-- ─── TRIPS TABLE ────────────────────────────
-- Created by the trip organizer
create table trips (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamptz default now() not null,

  -- Trip details
  name text not null,
  destination text not null,
  start_date date not null,
  end_date date not null,
  budget_per_person integer not null,        -- in cents (e.g. 50000 = $500)
  deposit_amount integer not null,           -- in cents (e.g. 2500 = $25)

  -- Organizer info
  organizer_name text not null,
  organizer_email text not null,

  -- Deadlines
  commitment_deadline timestamptz,           -- deadline to join + pay
  preference_deadline timestamptz,           -- deadline to submit preferences

  -- Status: 'open' → 'preferences' → 'voting' → 'locked' → 'cancelled'
  status text default 'open' not null check (status in ('open', 'preferences', 'voting', 'locked', 'cancelled')),

  -- Winning option (set when trip is locked)
  winning_option_id uuid
);

-- ─── MEMBERS TABLE ──────────────────────────
-- People who have committed (paid deposit) to a trip
create table members (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamptz default now() not null,

  trip_id uuid references trips(id) on delete cascade not null,

  -- Member info
  name text not null,
  email text not null,

  -- Payment
  stripe_session_id text,                    -- Stripe Checkout session ID
  stripe_payment_intent text,                -- Stripe payment intent ID
  paid boolean default false not null,
  paid_at timestamptz,

  -- Status: 'pending' → 'committed' → 'withdrawn' → 'interested'
  status text default 'pending' not null check (status in ('pending', 'committed', 'withdrawn', 'interested')),

  -- Unique: one entry per email per trip
  unique(trip_id, email)
);

-- ─── PREFERENCES TABLE ──────────────────────
-- Travel preferences submitted by each committed member
create table preferences (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamptz default now() not null,

  trip_id uuid references trips(id) on delete cascade not null,
  member_id uuid references members(id) on delete cascade not null,

  -- Preferences
  budget_flexibility text not null check (budget_flexibility in ('strict', 'flexible', 'whatever')),
  accommodation_style text not null check (accommodation_style in ('hostel', 'airbnb', 'hotel', 'no_preference')),
  activity_interests text[] not null default '{}',   -- array: food, nightlife, outdoors, culture, relaxation, adventure
  pace text not null check (pace in ('packed', 'balanced', 'chill')),
  hard_nos text,                                      -- free text, things they absolutely don't want

  -- One preference set per member per trip
  unique(trip_id, member_id)
);

-- ─── OPTIONS TABLE ──────────────────────────
-- AI-generated itinerary options for the group to vote on
create table options (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamptz default now() not null,

  trip_id uuid references trips(id) on delete cascade not null,

  -- Option details (generated by Claude)
  option_name text not null,
  description text not null,
  accommodation text not null,
  daily_activities jsonb not null default '[]',       -- array of day objects
  estimated_cost_per_person integer not null,          -- in cents
  why_this_works text not null,

  -- Vote tracking
  vote_count integer default 0 not null
);

-- ─── VOTES TABLE ────────────────────────────
-- Individual votes from members
create table votes (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamptz default now() not null,

  trip_id uuid references trips(id) on delete cascade not null,
  member_id uuid references members(id) on delete cascade not null,
  option_id uuid references options(id) on delete cascade not null,

  -- One vote per member per trip
  unique(trip_id, member_id)
);

-- ─── INDEXES ────────────────────────────────
create index idx_members_trip_id on members(trip_id);
create index idx_members_email on members(email);
create index idx_members_stripe_session on members(stripe_session_id);
create index idx_preferences_trip_id on preferences(trip_id);
create index idx_options_trip_id on options(trip_id);
create index idx_votes_trip_id on votes(trip_id);
create index idx_votes_option_id on votes(option_id);

-- ─── ROW LEVEL SECURITY ─────────────────────
-- Enable RLS on all tables (required by Supabase)
alter table trips enable row level security;
alter table members enable row level security;
alter table preferences enable row level security;
alter table options enable row level security;
alter table votes enable row level security;

-- For MVP: allow all operations via service role key (used in API routes)
-- In production, you'd add proper policies based on auth
create policy "Allow all for service role" on trips for all using (true) with check (true);
create policy "Allow all for service role" on members for all using (true) with check (true);
create policy "Allow all for service role" on preferences for all using (true) with check (true);
create policy "Allow all for service role" on options for all using (true) with check (true);
create policy "Allow all for service role" on votes for all using (true) with check (true);

-- ─── HELPER FUNCTION: CHECK MAJORITY ────────
-- Returns the option_id with majority votes, or null
create or replace function check_majority(p_trip_id uuid)
returns uuid as $$
declare
  total_members integer;
  winning_option uuid;
begin
  -- Count committed members
  select count(*) into total_members
  from members
  where trip_id = p_trip_id and status = 'committed';

  -- Find option with > 50% votes
  select option_id into winning_option
  from votes
  where trip_id = p_trip_id
  group by option_id
  having count(*) > total_members / 2.0
  order by count(*) desc
  limit 1;

  return winning_option;
end;
$$ language plpgsql;
